const mongoose = require("mongoose");

// Fine map — enforced on both backend and reflected on frontend
const VIOLATION_FINES = {
  "Late Return (Curfew)"  : 200,
  "Noise Complaint"       : 200,
  "Room Damage"           : 5000,
  "Unauthorized Guest"    : 500,
  "Smoking / Alcohol"     : 1000,
  "Mess Rule Violation"   : 300,
  "Ragging"               : 2000,
  "Theft"                 : 3000,
  "Abusive Behaviour"     : 500,
  "Property Damage"       : 5000,
  "Other"                 : 0
};

const VIOLATION_TYPES = Object.keys(VIOLATION_FINES);

const violationSchema = new mongoose.Schema({
  studentId:   { type: mongoose.Schema.Types.ObjectId, ref: "Student", required: true },
  studentName: { type: String,  required: true },
  roomNumber:  { type: Number,  required: true },
  type:        { type: String,  enum: VIOLATION_TYPES, required: true },
  description: { type: String,  default: "" },
  severity:    { type: String,  enum: ["low", "medium", "high"], default: "medium" },
  fine:        { type: Number,  default: 0 },        // INR fine amount
  isPaid:      { type: Boolean, default: false },
  isAuto:      { type: Boolean, default: false },    // auto-generated by system (late entry)
  reportedAt:  { type: Date,    default: Date.now }
});

module.exports = mongoose.model("Violation", violationSchema);
module.exports.VIOLATION_TYPES = VIOLATION_TYPES;
module.exports.VIOLATION_FINES = VIOLATION_FINES;
